server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 941002
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        # 指定sentinel 控制台地址
        dashboard: localhost:8181
  application:
    name: user-center

## 整体来说，这段配置的作用是开启并公开Spring Boot应用的所有管理端点，通过HTTP接口对外部访问开放。
## 在生产环境中使用时，应谨慎考虑安全因素，可能需要限制暴露的端点以避免潜在的安全风险。
management:
  endpoints:
    web:
      exposure:
        include: '*'
