server:
  port: 8082

user-center: # nacos中的服务id(即指定某个服务使用特定的负载均衡算法)
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #设置随机负载均衡

# Ribbon 默认是采用懒加载的方式，也就是只有第一次访问时才会去创建 LoadBalanceClient，因此第一次请求的时间会很长。
ribbon:
  eager-load:
    enabled: true # 开启饥饿模式，在项目启动时就创建
    clients: user-center # 指定某个服务开启饥饿模式，多个用逗号隔开

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 941002
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        metadata:
          test: test
  application:
    name: content-center

# SpringBoot的默认日志级别是info级别，feign的日志级别是debug级别，info > debug，所以在默认情况下，feign的日志不会输出
logging:
  level:
    com.itmuch.feignClient: debug

feign:
  client:
    config:
      UserInfoFeignClient: # 配置user-center服务端的日志级别
        loggerLevel: full
        connectTimeout: 5000 # 连接超时时间