server:
  port: 8082

user-center: # nacos中的服务id(即指定某个服务使用特定的负载均衡算法)
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #设置随机负载均衡

# Ribbon 默认是采用懒加载的方式，也就是只有第一次访问时才会去创建 LoadBalanceClient，因此第一次请求的时间会很长。
ribbon:
  eager-load:
    enabled: true # 开启饥饿模式，在项目启动时就创建
    clients: user-center # 指定某个服务开启饥饿模式，多个用逗号隔开

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 941002
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        metadata:
          test: test
    sentinel:
      transport:
        # 指定sentinel 控制台地址
        dashboard: localhost:8181
        # 指定和控制台通信的IP
        client-ip: 127.0.0.1
        # 指定和控制台通信的端口，默认值8719
        # 如不设置，会自动从8719开始扫描，依次+1，直到找到一个空闲端口
        port: 8719
        # 心跳发送周期，模式10秒
        heartbeat-interval-ms: 10000
  application:
    name: content-center

# SpringBoot的默认日志级别是info级别，feign的日志级别是debug级别，info > debug，所以在默认情况下，feign的日志不会输出
logging:
  level:
    com.itmuch.feignClient: debug

feign:
  sentinel:
    enabled: true
  client:
    config:
      UserInfoFeignClient: # 配置user-center服务端的日志级别
        loggerLevel: full
        connectTimeout: 5000 # 连接超时时间
  httpclient: # 配置连接池
    # 让feign使用apache httclient做请求，而不是默认urlconnection
    enabled: true
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 每个路由的最大连接数
## 整体来说，这段配置的作用是开启并公开Spring Boot应用的所有管理端点，通过HTTP接口对外部访问开放。
## 在生产环境中使用时，应谨慎考虑安全因素，可能需要限制暴露的端点以避免潜在的安全风险。
management:
  endpoints:
    web:
      exposure:
        include: '*'
